spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ruralPro
#    username: root
#    password: st1122

#    url: jdbc:mysql://150.158.163.190:3306/ruralPro
    url: jdbc:mysql://150.158.163.190:3306/ruralpro?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: St@12345

server:
  port: 9654