package com.example.ruralrevitalization.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@TableName("yunnanpovertycounty")
public class CountyYearData {
    private  String Name;
    private String englishName;
    private int Year;
    private String TownScale;
    private double gross;
    private double primaryGross;
    private double tertiaryGross;
    private double grossIndex;
    private double primaryGrossIndex;
    private double secondaryGrossIndex;
    private double tertiaryGrossIndex;
    private double grossPerCapia;
    private double totPopulationAtEndYr;
    private double totHouseholdsNum;
    private double totPopulation;
    private double totMaleNum;
    private double totFemaleNum;
    private double landArea;
    private double meadowArea;
    private double avgTemp;
    private double annualPrecipitation;
    private double unitPractitioners;
    private double employeesNum;
    private double statedOwnedEmployeesNum;
    private double urbanEmployeesNum;
    private double otherEmployeesNum;
    private double avgEmployeesWage;
    private double avgStatedOwnedEmployeesWage;
    private double avgUrbanEmployeesWage;
    private double avgOtherEmployeesWage;
    private double assetInvestGrowthRate;
    private double countyBudget;
    private double countyBudgerPerCapia;
    private double countyExpenditure;
    private double countyExpenditurePerCapia;
    private double totRetailSales;
    private double householdDepositsBalance;
    private double countyDisposableIncomePerCapia;
    private double AFAHtotValue;
    private double ruralHouseNum;
    private double ruralPopulation;
    private double ruralPractitioners;
    private double grainProduction;
    private double grainSownArea;
    private double grainPlantArea;
    private double riceArea;
    private double wheatArea;
    private double cornArea;
    private double SoybeanArea;
    private double cocoonArea;
    private double potatoArea;
    private double grainYield;
    private double riceYield;
    private double wheatYield;
    private double cornYield;
    private double beanYield;
    private double cocoonYield;
    private double potatoYield;
    private double oilYield;
    private double peanutYield;
    private double rapeseedYield;
    private double sugarYield;
    private double roastedTobaccoYield;
    private double teaYield;
    private double gardenFruitYield;
    private double pigStorageColumn;
    private double pigOutColumn;
    private double porkProduction;
    private double cattleStorageColumn;
    private double cattleOutColumn;
    private double beefProduction;
    private double sheepStorageColumn;
    private double sheepOutColumn;
    private double lambProduction;
    private double poultryStorageColumn;
    private double poultryOutColumn;
    private double poultryMeatProduction;
    private double eggProduction;
    private double milketcProduction;
    private double milkProduction;
    private double honeyProduction;
    private double aquaticProduction;
    private double businessNum;
    private double industrialGrossOutput;
    private double statedOwnedEnterpiseNum;
    private double statedOwnedEnterpiseTotOutputValue;
    private double collectiveEnterpisesNum;
    private double collectiveEnterpisesTotOutputValue;
    private double jointStockCompanyNum;
    private double jointStockCompanyTotOutputValue;
    private double rawCoal;
    private double powerGeneration;
    private double agriculturalFertilizer;
    private double liquor;
    private double beer;
    private double sugar;
    private double cement;
    private double totAssets;
    private double totLiabilities;
    private double totOwnersEquity;
    private double mainBusinessIncome;
    private double totProfit;
    private double totProfitAndTax;

}
